config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks',
                                    confirmations: 'confirmations' }

  concern :votable do
    member { post :vote }
    member { post :revote }
  end

  resources :questions, concerns: [:votable] do
    resources :comments, only: [:create]
    resources :answers, shallow: true, concerns: [:votable] do
      patch :best, on: :member
      resources :comments, only: [:create]
    end
  end

  resources :attachments, only: :destroy
  resources :awards, only: :index
  resources :subscriptions, only: [:create, :destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: %i(new edit) do
        resources :answers, except: %i(new edit), shallow: true
      end
    end
  end

  get '/search', to: 'search#search'

  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :subscription, dependent: :destroy
  has_one :award, dependent: :destroy
  belongs_to :user

  has_many_attached :files

  accepts_nested_attributes_for :award, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :new_answer_subscribe

  private

  def new_answer_subscribe
    subscription.create!(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :find_question, only: %i(show update destroy)

  authorize_resource

  def index
    @questions = Question.includes(:answers, :links, :comments, :user).with_attached_files
    render json: @questions
  end

  def show
    render json: @question
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_resource_owner

    if @question.save
      render json: @question, status: :created
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @question.update(question_params)
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    if @question.destroy!
      head :ok
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  private

  def find_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show edit update destroy]

  after_action :publish_question, only: %i(create)

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answer.links.new
  end

  def new
    @question = Question.new
    @question.links.new
    @question.award = Award.new
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)

    redirect_to @question, notice: 'Your question successfully created.' if @question.save
  end

  def update
    @question.update(question_params)
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Question succesfully deleted.'
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
    gon.question_id = @question.id
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                      links_attributes: [:id, :name, :url, :_destroy],
                                      award_attributes: [:title, :image])
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question_title',
        locals: { question: @question }
      )
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
h1= question.title
p= question.body
= render 'shared/files', resource: question
= render 'shared/links', resource: question
= render 'shared/rating', resource: question
= render 'comments/comments', resource: question
= render 'shared/subscription', question: question

- if question.award.present?
  p= "The author of the best answer will get #{question.award.title} award"

- if can? :update, question
  p= link_to 'Edit question', '#', class: 'edit-question-link', data: { question_id: question.id }
  p= link_to 'Delete question', question_path(question), method: :delete

= form_with model: question, class: 'hidden', local: false  do |f|
  p
    = f.label :title
    = f.text_area :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  p Links:
  p
    = f.fields_for :links do |l|
      = render 'shared/link_fields', f: l
    .link
        = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'

  = f.submit 'Save'

app/views/questions/_question_title.html.slim
div id="question-#{question.id}"
  p= link_to question.title, question_path(question)

app/views/questions/create.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

app/views/questions/index.html.slim
- cache [@questions, current_user]
  - if can? :create, Question
    p= link_to 'Ask question', new_question_path

  .questions
    - @questions.each do |question|
      = render 'question_title', question: question

app/views/questions/new.html.slim
.question-errors
  = render 'shared/errors', resource: @question

= form_with model: @question, local: false do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  p Links:
  p
    = f.fields_for :links do |l|
      = render 'shared/link_fields', f: l
    .link
      = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'

  p Award:
  p
    = f.fields_for :award do |a|
      p
        = a.label :title, 'Award title'
        = a.text_field :title
      p
        = a.label :image, 'Award image'
        = a.file_field :image, direct_upload: true, accept: 'image/png,image/gif,image/jpeg'

  p= f.submit 'Ask'

app/views/questions/show.html.slim
- cache [@question, current_user]
  .question-errors
    = render 'shared/errors', resource: @question

  .question
    = render @question

  .answer-errors
    = render 'shared/errors', resource: @answer

  = form_with model: [@question, @answer], class: 'new-answer', local: false do |f|
    p
      = f.label :body
      = f.text_area :body
    p
      = f.label :files
      = f.file_field :files, multiple: true, direct_upload: true

    p Links:
    p
      = f.fields_for :links do |l|
        = render 'shared/link_fields', f: l
      .link
        = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'

    p= f.submit 'Answer'

  .answers
    = render @question.answers

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if @question.errors.blank? %>
  $('.question').html('<%= j render @question %>');
  window.loadGists();
<% end %>