config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks',
                                    confirmations: 'confirmations' }

  concern :votable do
    member { post :vote }
    member { post :revote }
  end

  resources :questions, concerns: [:votable] do
    resources :comments, only: [:create]
    resources :answers, shallow: true, concerns: [:votable] do
      patch :best, on: :member
      resources :comments, only: [:create]
    end
  end

  resources :attachments, only: :destroy
  resources :awards, only: :index
  resources :subscriptions, only: [:create, :destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: %i(new edit) do
        resources :answers, except: %i(new edit), shallow: true
      end
    end
  end

  get '/search', to: 'search#search'

  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_files.html.slim
- if resource.files.attached?
  - resource.files.each do |file|
    div id="file-#{file.id}"
      p= link_to file.filename.to_s, url_for(file)
      - if can? :update, resource
        p= link_to 'Remove file', attachment_path(file), method: :delete, remote: true

app/views/shared/_link_fields.html.slim
.nested_fields
  .field
    = f.label :name, 'Link name'
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  = link_to_remove_association 'Delete link', f

app/views/shared/_links.html.slim
- if resource.links.present?
  .links
    p Links:
    ul
      - resource.links.each do |link|
        - if link.is_gist?
          li
            div class="gist" data-src="#{link.url}.json"
        - else  
          li = link_to link.name, link.url

app/views/shared/_rating.html.slim
.rating id="#{resource.class.to_s.downcase}-#{resource.id}"
  .rating-count
    = "Rating: #{resource.rating}"

  - if can? :vote, resource
    .vote-links class="#{'hidden' if current_user&.voted?(resource)}"
      = link_to 'Love it!', polymorphic_url(resource, action: :vote, voted: { value: 1 }),
                                            data: { type: :json }, method: :post, remote: true
      |
      = link_to 'Hate it!', polymorphic_url(resource, action: :vote, voted: { value: -1 }),
                                            data: { type: :json }, method: :post, remote: true
    .revote-link class="#{'hidden' unless current_user&.voted?(resource)}"
      p You voted
      = link_to 'Revote', polymorphic_url(resource, action: :revote),
                                          data: { type: :json }, method: :post, remote: true

app/views/shared/_search.html.slim
.search-form
  = form_with url: search_path, method: :get, scope: :search, local: true do |f|
    p= f.label :query, 'What are you looking for?'
    p= f.text_field :query
    p= f.select :scope, options_for_select(Services::Searching::SCOPES),
                        include_blank: 'Everywhere'

    p= f.submit 'Search'

app/views/shared/_subscription.html.slim
- if can?(:create, Subscription)
  .subscription
    -unless current_user.subscribed?(question)
      p= link_to 'Subscribe', subscriptions_path(id: question.id),
                              remote: true,
                              method: :post
    -else
      p= link_to 'Unsubscribe', subscription_path(id: question.id),
                                remote: true,
                                method: :delete