config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks',
                                    confirmations: 'confirmations' }

  concern :votable do
    member { post :vote }
    member { post :revote }
  end

  resources :questions, concerns: [:votable] do
    resources :comments, only: [:create]
    resources :answers, shallow: true, concerns: [:votable] do
      patch :best, on: :member
      resources :comments, only: [:create]
    end
  end

  resources :attachments, only: :destroy
  resources :awards, only: :index
  resources :subscriptions, only: [:create, :destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: %i(new edit) do
        resources :answers, except: %i(new edit), shallow: true
      end
    end
  end

  get '/search', to: 'search#search'

  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user

  has_many_attached :files

  validates :body, presence: true
  validates :best, uniqueness: { scope: :question_id, best: true }, if: :best?

  after_commit :send_for_subscribers, on: :create

  default_scope { order('best DESC, created_at') }

  def make_best!
    transaction do
      question.answers.update_all(best: false)
      update!(best: true)
      question.award&.update!(user: user)
    end
  end

  private

  def send_for_subscribers
    NewAnswerJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: %i(show)
  before_action :find_question, only: %i[new create]
  before_action :find_answer, only: %i(show edit update destroy best)

  include Voted

  after_action :publish_answer, only: %i(create)

  authorize_resource

  def new
    @answer = Answer.new
  end

  def show
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def best
    @question = @answer.question
    @answer.make_best!
  end

  def destroy
    @answer.destroy
  end

  def destroy
    @answer.destroy
    redirect_to @answer.question, notice: 'Answer succesfully deleted.'
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:id, :name, :url, :_destroy])
  end

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "question_#{@answer.question.id}",
      html: html(@answer),
      answer: @answer
    )
  end

  def html(answer)
    wardenize
    @job_renderer.render(
      partial: 'answers/answer',
      locals: { answer: answer }
    )
  end

  def wardenize
    @job_renderer = ::AnswersController.renderer.new
    renderer_env = @job_renderer.instance_eval { @env }
    warden = ::Warden::Proxy.new(renderer_env, ::Warden::Manager.new(Rails.application))
    renderer_env['warden'] = warden
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_question, only: %i(index create)
  before_action :find_answer, only: %i(show update destroy)

  authorize_resource

  def index
    @answers = @question.answers.includes(:links, :comments, :user).with_attached_files
    render json: @answers
  end

  def show
    render json: @answer
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_resource_owner

    if @answer.save
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @answer.update(answer_params)
      render json: @answer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    if @answer.destroy!
      head :ok
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  private

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache [answer, current_user]
  div class="answer" id="answer-#{answer.id}"
    p= answer.body
    = render 'shared/files', resource: answer
    = render 'shared/links', resource: answer
    = render 'shared/rating', resource: answer
    = render 'comments/comments', resource: answer

    - if can? :best, answer
      - unless answer.best?
        p= link_to 'Best answer', best_answer_path(answer), class: 'best-answer-link',
                                                            method: :patch,
                                                            remote: true
      - else
        p It's the best answer
        - if answer.question.award.present?
          p= "#{answer.user.email} got the #{answer.question.award.title}"

    -if can? :update, answer
      p= link_to 'Delete answer', answer_path(answer), method: :delete, remote: true
      p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }

    = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" }, local: false  do |f|
      p
        = f.label :body
        = f.text_area :body
      p
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true

      p Links:
      p
        = f.fields_for :links do |l|
          = render 'shared/link_fields', f: l
        .link
          = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'

        = f.submit 'Save'

app/views/answers/best.js.erb
$('.answers').html('<%= j render @question.answers %>');
loadGists();

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  loadGists();
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('#answer-<%= @answer.id %>').remove();

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.errors.blank? %>
  $('.answers').html('<%= j render @question.answers %>');
  loadGists();
<% end %>